<header>
    <nav class="navbar">
        <input type="checkbox" id="menu-toggle" class="menu-checkbox">
        <label for="menu-toggle" class="menu-icon">&#9776;</label>

        <div class="logo-container">
            <img src="images/logo1.png" alt="Website Logo" class="logo">
        </div>

        <ul>
            <li><a href="index.php">Home</a></li>
            <li><a href="jobs.php">Jobs</a></li>
            <li><a href="apply.php">Application</a></li>
            <li><a href="about.php">About</a></li>
            <li><a href="enhancements.php">Enhancements</a></li>
            <li><a href="phpenhancements.php">PHP Enhancements</a></li>
        </ul>

        <a href="login.php" class="login-button">Login</a>
    </nav>
</header>